package com.example.HostelManagement.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class SharingDetailsDTO {
    private Integer adminId;
    private Integer sharingTypeId;
    private Integer sharingCapacity;
    private BigDecimal sharingFee;
    private String description; // For creation
    private String typeName;    // For display
    private String success;     // Added this field
    private LocalDateTime createdAt; // Added missing field

    // Default constructor
    public SharingDetailsDTO() {}

    // Constructor for query results (matches your existing code)
    public SharingDetailsDTO(Integer adminId, Integer sharingTypeId, Integer sharingCapacity,
                             BigDecimal sharingFee, String success) {
        this.adminId = adminId;
        this.sharingTypeId = sharingTypeId;
        this.sharingCapacity = sharingCapacity;
        this.sharingFee = sharingFee;
        this.success = success;
        this.typeName = sharingCapacity + "-Sharing";
    }

    // Constructor for creation (from frontend)
    public SharingDetailsDTO(Integer adminId, Integer sharingCapacity, BigDecimal sharingFee, String description) {
        this.adminId = adminId;
        this.sharingCapacity = sharingCapacity;
        this.sharingFee = sharingFee;
        this.description = description;
        this.typeName = sharingCapacity + "-Sharing";
    }

    // Full constructor
    public SharingDetailsDTO(Integer sharingTypeId, Integer adminId, Integer sharingCapacity,
                             BigDecimal sharingFee, String description, String typeName, 
                             String success, LocalDateTime createdAt) {
        this.sharingTypeId = sharingTypeId;
        this.adminId = adminId;
        this.sharingCapacity = sharingCapacity;
        this.sharingFee = sharingFee;
        this.description = description;
        this.typeName = typeName;
        this.success = success;
        this.createdAt = createdAt;
    }

    // Constructor for database results
    public SharingDetailsDTO(Integer sharingTypeId, Integer adminId, String typeName, 
                             Integer capacity, BigDecimal sharingFee, String description, 
                             LocalDateTime createdAt) {
        this.sharingTypeId = sharingTypeId;
        this.adminId = adminId;
        this.typeName = typeName;
        this.sharingCapacity = capacity;
        this.sharingFee = sharingFee;
        this.description = description;
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public Integer getAdminId() { return adminId; }
    public void setAdminId(Integer adminId) { this.adminId = adminId; }

    public Integer getSharingTypeId() { return sharingTypeId; }
    public void setSharingTypeId(Integer sharingTypeId) { this.sharingTypeId = sharingTypeId; }

    public Integer getSharingCapacity() { return sharingCapacity; }
    public void setSharingCapacity(Integer sharingCapacity) {
        this.sharingCapacity = sharingCapacity;
        if (sharingCapacity != null && this.typeName == null) {
            this.typeName = sharingCapacity + "-Sharing";
        }
    }

    public BigDecimal getSharingFee() { return sharingFee; }
    public void setSharingFee(BigDecimal sharingFee) { this.sharingFee = sharingFee; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getTypeName() { 
        if (typeName == null && sharingCapacity != null) {
            return sharingCapacity + "-Sharing";
        }
        return typeName; 
    }
    public void setTypeName(String typeName) { this.typeName = typeName; }

    public String getSuccess() { return success; }
    public void setSuccess(String success) { this.success = success; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    // Helper method to auto-generate type name if not set
    public String getAutoGeneratedTypeName() {
        if (sharingCapacity != null) {
            return sharingCapacity + "-Sharing";
        }
        return typeName;
    }

    // Validation method
    public boolean isValidForCreation() {
        return adminId != null && 
               sharingCapacity != null && sharingCapacity > 0 &&
               sharingFee != null && sharingFee.compareTo(BigDecimal.ZERO) > 0;
    }

    @Override
    public String toString() {
        return "SharingDetailsDTO{" +
                "adminId=" + adminId +
                ", sharingTypeId=" + sharingTypeId +
                ", sharingCapacity=" + sharingCapacity +
                ", sharingFee=" + sharingFee +
                ", description='" + description + '\'' +
                ", typeName='" + typeName + '\'' +
                ", success='" + success + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}